dragen -f -r /staging/human/reference/hg19_DNA_RNA_CNV/ -1 ${1} -2 ${3} \
--output-file-prefix ${3} \
--output-directory ${4} \
--RGID illumina_RGID --RGSM ${3} \
--enable-map-align true \
--enable-map-align-output true \
--output-format bam --enable-sort true \
--enable-duplicate-marking true \
--enable-variant-caller true \
--enable-vcf-compression true \
--vc-enable-high-sensitivity-mode=true
--vc-target-bed ${5} --vc-target-bed-padding 0 \
--qc-coverage-region-1 ${5} \
--qc-coverage-region-padding-1 150 \
--qc-coverage-reports-1 full_res cov_report \
--qc-coverage-region-2 ${5} \
--qc-coverage-region-padding-2 500 \
--qc-coverage-reports-2 full_res cov_report
